### PR TITLE
Support customize function SplitId in cluster

### PR DESCRIPTION
**Pull request by siteshen**
We are using a variety of Instagram sharding algorithm, so we wanna custom function `SplitId()` in cluster.

### CODE REVIEW

**Comment by vmihailenco** [comment]
This only updates split function, but not its counterpart which generates ids. What changes did you make to  the built-in id generation rules? Do you change only [these constants](https://github.com/go-pg/sharding/blob/master/idgen.go#L9-L18)? If so I think we can make them configurable...

**Comment by siteshen** [comment]
It's almost another (but simpler) sharding algorithm. We use function `next_id()` in sql, so our application code care about nothing but `splitId(id)`

```python
seq_id = nextval('table_id_seq')
id = seq_id << n_shard_bit | shard_id
```

**Comment by vmihailenco** [comment]
Then I think it is better if you just use `your_package.SplitId(cluster, id)`. There are no compeling reasons it must be `cluster.SplitId(id)`...

**Comment by siteshen** [comment]
You are right. I need a more generic sharding library, or just hack in client code.

btw, if some one wanna implement it, sqlalchemy sharding provide a good enough API, though cross sharding transaction may be the hardest problem.
http://docs.sqlalchemy.org/en/latest/orm/extensions/horizontal_shard.html

**Pull request closed without merging**
